In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
data = pd.read_csv('letterdata_train.csv')

In [32]:
data.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex,RowID
0,B,5.0,9.0,5.0,7.0,4.0,6.0,7.0,9.0,7.0,7.0,6.0,7.0,2.0,8.0,9.0,9.0,6382.0
1,S,3.0,7.0,4.0,5.0,5.0,8.0,8.0,5.0,3.0,8.0,5.0,8.0,4.0,9.0,10.0,6.0,5348.0
2,W,8.0,11.0,8.0,8.0,6.0,3.0,10.0,2.0,3.0,9.0,9.0,8.0,8.0,11.0,2.0,5.0,10874.0
3,D,3.0,3.0,4.0,2.0,2.0,7.0,7.0,6.0,7.0,7.0,6.0,5.0,2.0,8.0,3.0,7.0,7915.0
4,E,4.0,9.0,4.0,6.0,4.0,3.0,6.0,5.0,9.0,6.0,7.0,13.0,0.0,8.0,7.0,9.0,2165.0

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 18 columns):
letter    15922 non-null object
xbox      15917 non-null float64
ybox      15923 non-null float64
width     15927 non-null float64
height    15916 non-null float64
onpix     15907 non-null float64
xbar      15921 non-null float64
ybar      15931 non-null float64
x2bar     15908 non-null float64
y2bar     15911 non-null float64
xybar     15926 non-null float64
x2ybar    15921 non-null float64
xy2bar    15927 non-null float64
xedge     15933 non-null float64
xedgey    15913 non-null float64
yedge     15922 non-null float64
yedgex    15895 non-null float64
RowID     15907 non-null float64
dtypes: float64(17), object(1)
memory usage: 2.2+ MB

In [34]:
data.isnull().sum()

letter     78
xbox       83
ybox       77
width      73
height     84
onpix      93
xbar       79
ybar       69
x2bar      92
y2bar      89
xybar      74
x2ybar     79
xy2bar     73
xedge      67
xedgey     87
yedge      78
yedgex    105
RowID      93
dtype: int64

In [35]:
data['xbox'].fillna(data['xbox'].mean(),inplace=True)
data['ybox'].fillna(data['ybox'].mean(),inplace=True)
data['width'].fillna(data['width'].mean(),inplace=True)
data['height'].fillna(data['height'].mean(),inplace=True)
data['onpix'].fillna(data['onpix'].mean(),inplace=True)
data['xbar'].fillna(data['xbar'].mean(),inplace=True)
data['ybar'].fillna(data['ybar'].mean(),inplace=True)
data['x2bar'].fillna(data['x2bar'].mean(),inplace=True)
data['y2bar'].fillna(data['y2bar'].mean(),inplace=True)
data['xybar'].fillna(data['xybar'].mean(),inplace=True)
data['x2ybar'].fillna(data['x2ybar'].mean(),inplace=True)
data['xy2bar'].fillna(data['xy2bar'].mean(),inplace=True)
data['xedge'].fillna(data['xedge'].mean(),inplace=True)
data['xedgey'].fillna(data['xedgey'].mean(),inplace=True)
data['yedge'].fillna(data['yedge'].mean(),inplace=True)
data['yedgex'].fillna(data['yedgex'].mean(),inplace=True)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
data.dropna(inplace=True)
rfc = RandomForestClassifier(n_estimators=200)

In [39]:
X = data.drop('letter',axis=1)
y = data['letter']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [40]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [41]:
data_test = pd.read_csv("letterdata_test.csv")
data_test

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex,RowID
0,5,6,7,5,5,7,5,4,4,9,4,9,3,7,6,6,10841
1,3,8,5,6,1,4,10,3,2,9,13,8,2,11,0,8,16537
2,5,8,8,6,3,3,9,4,4,11,11,10,5,8,1,7,4589
3,6,11,6,8,3,4,13,9,2,10,6,4,1,10,4,8,4050
4,3,8,4,6,4,8,7,7,5,7,7,9,2,9,8,8,9298
5,5,8,7,6,5,10,6,3,5,10,3,7,3,7,4,10,4340
6,6,11,9,8,9,9,7,5,5,6,7,5,11,8,4,6,2821
7,3,6,5,4,5,7,8,2,7,7,6,8,0,8,8,8,14954
8,5,10,6,8,8,8,8,6,6,7,6,6,6,8,3,8,3443
9,3,4,4,3,2,7,7,6,4,9,6,8,2,8,3,7,15628
10,3,5,3,6,3,8,8,5,2,8,8,10,3,8,5,8,12092
11,2,2,3,3,2,8,8,7,3,5,6,10,2,9,5,10,10794
12,5,2,6,4,4,8,6,7,5,7,7,8,8,6,2,7,7440
13,3,3,4,5,1,3,7,7,2,7,6,11,3,8,2,10,18148
14,4,9,5,7,3,7,7,3,12,9,6,8,0,8,8,8,8291
15,3,2,4,3,2,7,8,5,4,7,6,7,5,9,2,6,11287
16,1,2,2,3,1,11,6,2,5,11,3,8,0,7,1,7,14521
17,2,8,3,6,1,7,7,0,8,14,6,8,0,8,1,7,11492
18,4,4,6,7,3,8,8,8,8,6,7,8,2,7,6,10,10744
19,6,9,8,7,6,9,9,5,4,6,5,7,3,9,10,5,10185
20,3,8,4,6,3,7,8,3,11,8,6,8,0,8,7,7,13490
21,5,8,6,7,3,8,8,8,7,5,7,9,3,7,5,10,14911
22,6,7,4,10,3,6,10,3,3,13,6,5,3,8,7,9,12991
23,2,1,2,1,1,7,7,7,5,6,5,7,1,8,7,10,10641
24,4,8,5,6,2,5,3,1,9,6,1,10,0,7,2,7,3913
25,6,9,8,8,7,7,6,5,4,6,7,8,7,8,2,7,5262
26,9,11,12,8,8,4,6,4,5,10,11,11,11,6,4,8,498
27,6,11,6,8,4,2,9,5,7,11,11,13,1,8,2,7,3071
28,3,5,5,4,2,10,2,2,2,9,2,9,2,6,2,8,17444
29,5,10,5,5,4,9,6,5,6,10,6,7,4,8,9,9,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3970,1,3,2,1,1,10,7,2,4,11,5,9,1,7,0,7,10462
3971,3,2,4,4,2,6,8,6,7,6,9,9,3,9,1,7,1783
3972,4,8,4,6,3,7,6,12,4,7,12,8,3,9,0,8,1026
3973,5,7,7,9,8,10,10,5,3,6,7,8,6,11,8,5,13448
3974,4,6,6,5,4,7,5,5,4,8,4,7,3,7,4,8,17537
3975,5,6,7,4,6,7,6,5,5,8,6,11,10,5,2,9,2355
3976,3,8,4,6,2,7,7,4,13,10,6,8,0,8,8,8,176
3977,4,7,6,5,5,9,7,2,4,9,6,7,7,5,2,7,4646
3978,4,2,5,4,4,7,8,6,6,7,6,8,3,8,3,8,18298
3979,4,7,4,5,3,7,7,12,1,7,9,8,8,6,0,8,4347
3980,1,1,1,2,1,7,7,1,7,7,6,8,0,8,2,8,2349
3981,4,6,6,5,5,7,8,4,3,6,6,8,4,7,1,7,3038
3982,5,11,8,8,4,10,8,5,2,7,9,8,9,9,0,8,14344
3983,5,11,6,8,7,7,7,6,3,7,6,9,4,8,8,8,5751
3984,5,9,7,7,5,5,5,1,8,7,2,11,2,9,3,7,14614
3985,4,8,5,10,7,8,6,8,3,6,5,9,3,9,5,10,19559
3986,2,3,4,2,2,8,7,4,5,9,4,7,2,7,4,10,2722
3987,4,6,4,4,2,2,12,3,3,11,11,8,2,11,1,8,2877
3988,5,9,3,4,1,10,6,5,4,13,3,7,2,8,5,10,15772
3989,2,4,4,2,2,8,8,2,4,10,4,6,5,10,1,7,7643
3990,3,5,5,4,3,9,7,5,7,9,4,5,3,8,3,8,671
3991,7,13,7,8,5,10,5,2,5,9,4,8,6,8,6,9,15305
3992,4,7,6,6,7,7,6,4,3,7,6,9,6,11,8,12,9564
3993,2,1,3,2,1,4,10,3,5,10,8,5,0,9,3,7,19990
3994,6,10,6,5,4,9,6,4,7,11,4,9,3,7,8,11,15487
3995,3,7,4,5,2,5,8,7,7,9,8,13,1,10,4,10,11391
3996,3,7,5,5,2,9,6,3,9,11,3,9,1,7,6,9,7468
3997,6,10,5,5,3,7,8,4,3,9,8,9,4,9,9,11,5890
3998,10,13,11,7,5,7,7,3,5,13,9,9,6,8,0,8,17820
3999,7,10,7,7,6,5,10,4,3,9,7,7,9,13,3,4,17012

In [42]:
data_test.dropna(inplace=True)

In [43]:
rfc_pred = rfc.predict(X_test)

In [44]:
from sklearn.metrics import classification_report,confusion_matrix

In [45]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           A       0.96      0.99      0.98       168
           B       0.90      0.91      0.90       206
           C       0.99      0.95      0.97       193
           D       0.89      0.95      0.92       199
           E       0.95      0.94      0.94       191
           F       0.93      0.96      0.95       190
           G       0.92      0.96      0.94       178
           H       0.94      0.79      0.86       170
           I       0.94      0.95      0.94       172
           J       0.97      0.92      0.94       186
           K       0.90      0.92      0.91       185
           L       0.99      0.95      0.97       176
           M       0.95      0.97      0.96       185
           N       0.98      0.97      0.97       175
           O       0.91      0.98      0.95       161
           P       0.96      0.96      0.96       184
           Q       0.91      0.94      0.92       181
           R       0.90      0.95      0.92       203
           S       0.98      0.93      0.95       183
           T       0.96      0.99      0.98       177
           U       0.99      0.97      0.98       172
           V       0.97      0.95      0.96       177
           W       0.97      0.97      0.97       180
           X       0.94      0.95      0.94       192
           Y       0.99      0.96      0.98       194
           Z       0.98      0.96      0.97       172

   micro avg       0.95      0.95      0.95      4750
   macro avg       0.95      0.95      0.95      4750
weighted avg       0.95      0.95      0.95      4750

In [46]:
print(confusion_matrix(y_test,rfc_pred))

[[167   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [  0 188   0   1   0   1   2   3   0   0   0   0   1   0   0   0   0   3
    0   0   1   4   0   2   0   0]
 [  0   0 183   0   0   2   3   0   0   0   0   0   0   0   3   0   2   0
    0   0   0   0   0   0   0   0]
 [  1   0   0 190   1   1   0   2   0   0   0   0   0   1   2   0   0   0
    1   0   0   0   0   0   0   0]
 [  0   1   0   0 179   1   3   0   0   0   1   0   0   0   0   0   1   0
    2   1   0   0   0   2   0   0]
 [  0   1   0   2   1 182   0   0   0   0   1   0   0   0   0   3   0   0
    0   0   0   0   0   0   0   0]
 [  0   2   0   0   1   0 170   0   0   0   0   0   0   0   0   0   3   0
    0   0   0   0   2   0   0   0]
 [  0   2   0   9   0   0   1 135   0   0   6   0   1   0   2   2   2   9
    0   0   0   0   0   0   1   0]
 [  0   1   0   2   0   0   0   0 163   4   0   0   0   1   0   0   0   0
    0   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1  10 171   1   1   0   0   0   0   0   0
    0   0   0   0   0   1   0   1]
 [  0   2   1   0   2   0   0   2   0   0 171   0   0   0   0   1   0   3
    0   0   0   0   0   3   0   0]
 [  1   0   0   0   0   0   1   0   0   1   1 168   0   0   0   0   1   1
    0   0   0   0   0   2   0   0]
 [  1   0   0   0   0   0   3   0   0   0   1   0 179   0   0   0   0   0
    0   0   0   0   1   0   0   0]
 [  0   0   0   3   0   0   0   0   0   0   0   0   1 169   0   0   0   1
    0   0   0   0   1   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0   0   0   0 158   0   1   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   5   0   0   1   0   0   0   0   0   0 177   0   0
    0   0   0   1   0   0   0   0]
 [  1   1   0   1   1   0   1   0   0   0   0   0   0   0   4   0 170   0
    0   0   0   0   1   0   0   1]
 [  1   2   0   2   0   1   0   0   0   0   2   0   0   1   0   0   1 192
    0   0   0   0   0   1   0   0]
 [  2   3   0   0   0   1   0   1   0   1   0   0   0   0   0   0   2   2
  170   0   0   0   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 176   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0   3   0   0   0
    0   0 166   0   0   0   0   0]
 [  0   3   0   0   0   0   1   0   0   0   0   0   0   0   0   1   0   1
    0   0   0 169   1   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0   1   0   0   1
    0   0   0   1 174   0   0   0]
 [  0   3   0   0   1   1   0   0   0   0   4   0   0   0   0   0   0   0
    1   0   0   0   0 182   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   6   0   0   0   0 187   0]
 [  0   0   0   1   2   0   0   0   0   0   0   0   0   0   0   0   4   0
    0   0   0   0   0   0   0 165]]

In [47]:
rfc_pred2 = rfc.predict(data_test)

In [48]:
rfc_pred2

array(['O', 'Y', 'N', ..., 'C', 'N', 'W'], dtype=object)

In [49]:
final_pred = pd.DataFrame({'id':data_test['RowID'],'predictions':rfc_pred2})

In [50]:
final_pred

         id predictions
0     10841           O
1     16537           Y
2      4589           N
3      4050           P
4      9298           S
5      4340           R
6      2821           M
7     14954           Z
8      3443           D
9     15628           O
10    12092           Q
11    10794           Q
12     7440           M
13    18148           K
14     8291           Z
15    11287           N
16    14521           J
17    11492           I
18    10744           G
19    10185           Z
20    13490           Z
21    14911           Q
22    12991           J
23    10641           B
24     3913           L
25     5262           U
26      498           M
27     3071           C
28    17444           A
29       71           B
...     ...         ...
3970  10462           J
3971   1783           U
3972   1026           U
3973  13448           Y
3974  17537           O
3975   2355           M
3976    176           Z
3977   4646           M
3978  18298           H
3979   4347           M
3980   2349           I
3981   3038           U
3982  14344           W
3983   5751           G
3984  14614           L
3985  19559           Q
3986   2722           R
3987   2877           V
3988  15772           I
3989   7643           N
3990    671           D
3991  15305           K
3992   9564           E
3993  19990           F
3994  15487           Q
3995  11391           C
3996   7468           Z
3997   5890           C
3998  17820           N
3999  17012           W

[4000 rows x 2 columns]